### ISSUE TITLE
Reconnect Error

### ISSUE THREAD

**Issue by xiispace** [Crypto-toolbox/btfxwss#125]
hi team, i got the following error:
```
DEBUG:btfxwss.connection:_connection_timed_out(): Fired! Issuing reconnect..
DEBUG:btfxwss.connection:reconnect(): Initialzion reconnect sequence..
send: b'\x88\x82\x9f\\f\x1e\x9c\xb4'
DEBUG:websocket:send: b'\x88\x82\x9f\\f\x1e\x9c\xb4'
INFO:btfxwss.connection:Attempting to connect again in 3 seconds.
close status: 23346
ERROR:websocket:close status: 23346
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/xxx/venv/lib/python3.6/site-packages/btfxwss/connection.py", line 172, in run
    self._connect()
  File "/Users/xxx/venv/lib/python3.6/site-packages/btfxwss/connection.py", line 164, in _connect
    http_no_proxy=self.http_no_proxy)
  File "/Users/xxx/venv/lib/python3.6/site-packages/websocket/_app.py", line 203, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened
```
should check and close the `self.socket.sock` before `self.socket.run_forever`

**Comment by yffMing** [comment]
@xiispace  I have the same problem as you, can you tell me how to solve the problem?
