### ISSUE TITLE
when i try to connect to socket i m getting this error

### ISSUE THREAD

**Issue by shardulR1** [Crypto-toolbox/btfxwss#132]
==================

Traceback (most recent call last):
  File "/home/pi/Desktop/finalclient.py", line 12, in <module>
    ws.connect("Actual socket address'")
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 245, in read_headers
    status_message = status_info[2]
IndexError: list index out of range

**Comment by doyeob** [comment]
same here
