### ISSUE TITLE
can't import module

### ISSUE THREAD

**Issue by Vishant-Siddharth** [Crypto-toolbox/btfxwss#135]
from btfxwss import BtfxWss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devesh/env/buyucoin_env/lib/python3.4/site-packages/btfxwss/__init__.py", line 1, in <module>
    from btfxwss.client import BtfxWss
  File "/home/devesh/env/buyucoin_env/lib/python3.4/site-packages/btfxwss/client.py", line 6, in <module>
    from btfxwss.connection import WebSocketConnection
  File "/home/devesh/env/buyucoin_env/lib/python3.4/site-packages/btfxwss/connection.py", line 470
    self.send(**q, auth=True)
                 ^
SyntaxError: invalid syntax

using python version 3.4
ubuntu 16.04

**Comment by nlsdfnbch** [comment]
you require python 3.5 or later to use `btfxwss`
